# Generated by Django 5.1.1 on 2025-04-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('CIVIL', 'Civil'), ('ELECTRICAL', 'Electrical'), ('MECHANICAL', 'Mechanical'), ('BIO-TECH', 'Bio-Tech')], max_length=20)),
                ('query', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
