# Generated by Django 5.1.1 on 2025-04-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='submitted_at',
        ),
        migrations.AlterField(
            model_name='query',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('Civil', 'Civil Engineering'), ('Electrical', 'Electrical Engineering'), ('Mechanical', 'Mechanical Engineering'), ('Bio-Tech', 'Biotechnology')], max_length=50),
        ),
    ]
