# Generated by Django 5.1.1 on 2025-04-15 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_query_submitted_at_alter_query_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='query',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('CIVIL', 'Civil'), ('ELECTRICAL', 'Electrical'), ('MECHANICAL', 'Mechanical'), ('BIO-TECH', 'Bio-Tech')], max_length=20),
        ),
    ]
